Cap long lines
skorokithakis/tbvaccine pull request #14
Opened 2017-06-09 15:47 UTC by MinchinWeb

I'm having issues where I have *very* long variables (like a spreadsheet loaded in memory) and so when TBVaccine prints that, I lose everything else in my console buffer. Here is a quick and dirty hack to cap line length. It works by dropping ANSI sequences from long variable lines, and cap  their length at 79*4 chars (approx. 4 output lines). A note is added to the line that there is more un-printed data.

(I can't figure out how to get decent lengths with normal string slicing on strings with ANSI codes embedded. For example, the output line `|     __annotations__ = {}` clocks in with a length of 148 (!) due to ANSI control codes.)

The downside of dropping ANSI sequences like this is that the line won't be coloured....

2017-06-09 15:53 UTC, MinchinWeb commented
P.S. I think the variable printing is an awesome addition! Thanks for adding it!

2017-06-10 01:23 UTC, skorokithakis commented
This looks good to me, can you post a screenshot with the before and after so I can see how it looks on your data? Thanks!

2017-06-11 03:19 UTC, MinchinWeb commented
Before (~1,500 lines in this case):

![image](https://user-images.githubusercontent.com/1548809/27007953-00776268-4e22-11e7-8690-17c9b3aea143.png)

After:

![image](https://user-images.githubusercontent.com/1548809/27007958-2123959a-4e22-11e7-9486-4330b3e3d02f.png)

(before, when I was testing it, none of the variable lines where being color-ed, so I wasn't worried about losing that formatting)

2017-06-11 03:40 UTC, MinchinWeb commented
(I figure out what is going on with the colours... initializing colorama means that colours beyond the basic 16 aren't displayed)

2017-06-11 17:03 UTC, skorokithakis requested changes

2017-06-11 17:03 UTC, skorokithakis commented on .gitignore
> +__pycahce__/
I think you mean `__pycache__` here.

2017-06-11 17:03 UTC, skorokithakis commented
Looks great, just a minor typo and we're good to merge, thank you!

2017-06-12 15:53 UTC, MinchinWeb commented on .gitignore
> +__pycahce__/
that would be why is wasn't working!

2017-06-13 11:18 UTC, skorokithakis approved these changes

2017-06-13 11:18 UTC, merged

2017-06-13 11:18 UTC, skorokithakis commented
Thank you!